name: MavDialog
author: dustin
category: Interface
tags: [dialog, UI, GUI, window]
demo: http://maveno.us/library/public/mavdialog/
docs: http://maveno.us/library/public/mavdialog/
mooshell: http://mootools.net/shell/NPK6y/2/
current: 0.1.1